version: "3"

services: 
  app:
    build: .
    ports: 
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    command: gatsby develop -H 0.0.0.0
