version: "3.7"
services:
  gatsby:
    build:
      context: .
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules/
